import { prisma } from './prisma';

export interface AgencyBranding {
  name: string;
  primaryColor: string;
  accentColor: string;
  font: string;
  logoUrl: string | null;
  whiteLabelEnabled: boolean;
  reportFooterText: string;
}

const DEFAULTS: AgencyBranding = {
  name: 'RankFlow',
  primaryColor: '#FF1E42',
  accentColor: '#E01435',
  font: "'Inter', sans-serif",
  logoUrl: null,
  whiteLabelEnabled: false,
  reportFooterText: 'Generated by RankFlow · Confidential',
};

/**
 * Fetch agency branding from DB by domain slug.
 * Falls back to platform defaults when fields are unset.
 */
export async function getAgencyBranding(domain: string): Promise<AgencyBranding> {
  try {
    const agency = await prisma.agency.findFirst({
      where: { OR: [{ slug: domain }, { subdomain: domain }] },
      select: {
        name: true,
        brandingJson: true,
      }
    });

    if (!agency) return DEFAULTS;

    let parsed: any = {};
    if (agency.brandingJson) {
      try {
        parsed = JSON.parse(agency.brandingJson);
      } catch (e) {}
    }

    return {
      name: agency.name || DEFAULTS.name,
      primaryColor: parsed.primaryColor || parsed.brandingColor || DEFAULTS.primaryColor,
      accentColor: parsed.accentColor || parsed.brandingAccentColor || DEFAULTS.accentColor,
      font: parsed.font || parsed.brandingFont ? `'${parsed.font || parsed.brandingFont}', sans-serif` : DEFAULTS.font,
      logoUrl: parsed.logoUrl || parsed.brandingLogo || null,
      whiteLabelEnabled: parsed.whiteLabelEnabled ?? false,
      reportFooterText: parsed.reportFooterText || DEFAULTS.reportFooterText,
    };
  } catch {
    return DEFAULTS;
  }
}

/**
 * Build a CSS string of custom properties from agency branding.
 * Inject this as a <style> tag in the layout for dynamic white-labeling.
 */
export function buildBrandingCssVars(branding: AgencyBranding): string {
  // Parse hex to RGB components for rgba() usage
  const toRgb = (hex: string): string => {
    const h = hex.replace('#', '');
    const r = parseInt(h.substring(0, 2), 16);
    const g = parseInt(h.substring(2, 4), 16);
    const b = parseInt(h.substring(4, 6), 16);
    return isNaN(r) ? '99, 102, 241' : `${r}, ${g}, ${b}`;
  };

  return `
    :root {
      --brand-primary: ${branding.primaryColor};
      --brand-accent: ${branding.accentColor};
      --brand-primary-rgb: ${toRgb(branding.primaryColor)};
      --brand-accent-rgb: ${toRgb(branding.accentColor)};
      --brand-font: ${branding.font};
    }
  `.trim();
}
